#!/usr/bin/env bash
# ============================================================
# Télécharge tous les assets (images + fonts) de Savoria Framer
# À lancer depuis la racine du dossier savoria-scrape/
# Usage : bash download-assets.sh
# ============================================================

set -u
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
REF="https://savoriarestro.framer.website/"

mkdir -p assets/images assets/fonts

fetch() {
  local url="$1" out="$2"
  if [[ -s "$out" ]]; then
    echo "  [skip] $out"
    return 0
  fi
  if curl -sSL -f -A "$UA" -e "$REF" "$url" -o "$out"; then
    local size=$(stat -c%s "$out" 2>/dev/null || stat -f%z "$out" 2>/dev/null)
    echo "  [ok]   $out ($size b)"
  else
    echo "  [FAIL] $url"
    rm -f "$out"
  fi
}

echo "=== Images ==="
fetch "https://framerusercontent.com/assets/0j4MpHOHUl5qzxmb2xufNYrrsM.png" "assets/images/0j4MpHOHUl5qzxmb2xufNYrrsM.png"
fetch "https://framerusercontent.com/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png" "assets/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png"
fetch "https://framerusercontent.com/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png?scale-down-to=1024" "assets/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png"
fetch "https://framerusercontent.com/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png?scale-down-to=512" "assets/images/1TeDhiFzE9GV7mFPrWPf5UaPs8w.png"
fetch "https://framerusercontent.com/images/3veQ5mDnGLiIZo2h7y7d49tIaw.png" "assets/images/3veQ5mDnGLiIZo2h7y7d49tIaw.png"
fetch "https://framerusercontent.com/images/3veQ5mDnGLiIZo2h7y7d49tIaw.png?scale-down-to=1024" "assets/images/3veQ5mDnGLiIZo2h7y7d49tIaw.png"
fetch "https://framerusercontent.com/images/4RKqYayWW9SQszIdde4gZNF7oI.png" "assets/images/4RKqYayWW9SQszIdde4gZNF7oI.png"
fetch "https://framerusercontent.com/images/4RKqYayWW9SQszIdde4gZNF7oI.png?scale-down-to=1024" "assets/images/4RKqYayWW9SQszIdde4gZNF7oI.png"
fetch "https://framerusercontent.com/images/4RKqYayWW9SQszIdde4gZNF7oI.png?scale-down-to=512" "assets/images/4RKqYayWW9SQszIdde4gZNF7oI.png"
fetch "https://framerusercontent.com/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp" "assets/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp"
fetch "https://framerusercontent.com/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp?scale-down-to=1024" "assets/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp"
fetch "https://framerusercontent.com/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp?scale-down-to=512" "assets/images/6JYWJdZpLVIHWViwrIjjINJHtyY.webp"
fetch "https://framerusercontent.com/images/6RMJsTBylnAjePd99Bps75drXE.png" "assets/images/6RMJsTBylnAjePd99Bps75drXE.png"
fetch "https://framerusercontent.com/images/6RMJsTBylnAjePd99Bps75drXE.png?scale-down-to=1024" "assets/images/6RMJsTBylnAjePd99Bps75drXE.png"
fetch "https://framerusercontent.com/images/8ZRBF9h7rHgRxyPpRln96DMnR5w.png" "assets/images/8ZRBF9h7rHgRxyPpRln96DMnR5w.png"
fetch "https://framerusercontent.com/images/8ZRBF9h7rHgRxyPpRln96DMnR5w.png?scale-down-to=1024" "assets/images/8ZRBF9h7rHgRxyPpRln96DMnR5w.png"
fetch "https://framerusercontent.com/images/9V7SDG3tB838YFpryLeteV38NM.png" "assets/images/9V7SDG3tB838YFpryLeteV38NM.png"
fetch "https://framerusercontent.com/images/9V7SDG3tB838YFpryLeteV38NM.png?scale-down-to=1024" "assets/images/9V7SDG3tB838YFpryLeteV38NM.png"
fetch "https://framerusercontent.com/images/9V7SDG3tB838YFpryLeteV38NM.png?scale-down-to=2048" "assets/images/9V7SDG3tB838YFpryLeteV38NM.png"
fetch "https://framerusercontent.com/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png" "assets/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png"
fetch "https://framerusercontent.com/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png?scale-down-to=1024" "assets/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png"
fetch "https://framerusercontent.com/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png?scale-down-to=512" "assets/images/DgMyOvjAJgLu0uLiuL6hOAJqA.png"
fetch "https://framerusercontent.com/images/E28s7XqLaKOapltaPlGRYqEgOA.png" "assets/images/E28s7XqLaKOapltaPlGRYqEgOA.png"
fetch "https://framerusercontent.com/images/E28s7XqLaKOapltaPlGRYqEgOA.png?scale-down-to=1024" "assets/images/E28s7XqLaKOapltaPlGRYqEgOA.png"
fetch "https://framerusercontent.com/images/FlPL0Fo2UpqNSJ4U3TfNGtWosi8.png" "assets/images/FlPL0Fo2UpqNSJ4U3TfNGtWosi8.png"
fetch "https://framerusercontent.com/images/MNjoZNXzt2gq5J0haAKAH7T75s.png" "assets/images/MNjoZNXzt2gq5J0haAKAH7T75s.png"
fetch "https://framerusercontent.com/images/MNjoZNXzt2gq5J0haAKAH7T75s.png?scale-down-to=1024" "assets/images/MNjoZNXzt2gq5J0haAKAH7T75s.png"
fetch "https://framerusercontent.com/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp" "assets/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp"
fetch "https://framerusercontent.com/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp?scale-down-to=1024" "assets/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp"
fetch "https://framerusercontent.com/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp?scale-down-to=512" "assets/images/MhdF93OJQRcReXIzmA2TSJAbQ2M.webp"
fetch "https://framerusercontent.com/images/NmrgygAcnHyZ24XJ4polzeA08U.png" "assets/images/NmrgygAcnHyZ24XJ4polzeA08U.png"
fetch "https://framerusercontent.com/images/NmrgygAcnHyZ24XJ4polzeA08U.png?scale-down-to=1024" "assets/images/NmrgygAcnHyZ24XJ4polzeA08U.png"
fetch "https://framerusercontent.com/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png" "assets/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png"
fetch "https://framerusercontent.com/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png?scale-down-to=1024" "assets/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png"
fetch "https://framerusercontent.com/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png?scale-down-to=512" "assets/images/OSGNdAPLJgu7cTWN5d4Dli2XU6w.png"
fetch "https://framerusercontent.com/images/OXaxugtV9BC6qYFwJcHAQqzw.webp" "assets/images/OXaxugtV9BC6qYFwJcHAQqzw.webp"
fetch "https://framerusercontent.com/images/OXaxugtV9BC6qYFwJcHAQqzw.webp?scale-down-to=1024" "assets/images/OXaxugtV9BC6qYFwJcHAQqzw.webp"
fetch "https://framerusercontent.com/images/OXaxugtV9BC6qYFwJcHAQqzw.webp?scale-down-to=512" "assets/images/OXaxugtV9BC6qYFwJcHAQqzw.webp"
fetch "https://framerusercontent.com/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg" "assets/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg"
fetch "https://framerusercontent.com/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg?scale-down-to=1024" "assets/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg"
fetch "https://framerusercontent.com/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg?scale-down-to=512" "assets/images/QIPl2NblrnOqeF4k5KDIOTv3Cs.jpg"
fetch "https://framerusercontent.com/images/S1iIaM1E8mVLacqE9YrbDx3bro.png" "assets/images/S1iIaM1E8mVLacqE9YrbDx3bro.png"
fetch "https://framerusercontent.com/images/S1iIaM1E8mVLacqE9YrbDx3bro.png?scale-down-to=1024" "assets/images/S1iIaM1E8mVLacqE9YrbDx3bro.png"
fetch "https://framerusercontent.com/images/TH0dtcymw6YcwIqWLOAv7RnULQ.jpg" "assets/images/TH0dtcymw6YcwIqWLOAv7RnULQ.jpg"
fetch "https://framerusercontent.com/images/TH0dtcymw6YcwIqWLOAv7RnULQ.jpg?scale-down-to=1024" "assets/images/TH0dtcymw6YcwIqWLOAv7RnULQ.jpg"
fetch "https://framerusercontent.com/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg" "assets/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg"
fetch "https://framerusercontent.com/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg?scale-down-to=1024" "assets/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg"
fetch "https://framerusercontent.com/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg?scale-down-to=512" "assets/images/VVmSiZIDXxbCfGHyCSKoc2Aa1Y.jpg"
fetch "https://framerusercontent.com/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png" "assets/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png"
fetch "https://framerusercontent.com/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png?scale-down-to=1024" "assets/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png"
fetch "https://framerusercontent.com/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png?scale-down-to=512" "assets/images/WBxJ3qin8yeN6rGQ4kSLed0T7xY.png"
fetch "https://framerusercontent.com/images/XPuqH8MPUNYomlKhRjraucjKGsc.png" "assets/images/XPuqH8MPUNYomlKhRjraucjKGsc.png"
fetch "https://framerusercontent.com/images/XPuqH8MPUNYomlKhRjraucjKGsc.png?scale-down-to=1024" "assets/images/XPuqH8MPUNYomlKhRjraucjKGsc.png"
fetch "https://framerusercontent.com/images/XPuqH8MPUNYomlKhRjraucjKGsc.png?scale-down-to=512" "assets/images/XPuqH8MPUNYomlKhRjraucjKGsc.png"
fetch "https://framerusercontent.com/images/ZedukbhAqTWzhWu7XgfHVuuBpc.png" "assets/images/ZedukbhAqTWzhWu7XgfHVuuBpc.png"
fetch "https://framerusercontent.com/images/ZedukbhAqTWzhWu7XgfHVuuBpc.png?scale-down-to=512" "assets/images/ZedukbhAqTWzhWu7XgfHVuuBpc.png"
fetch "https://framerusercontent.com/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg" "assets/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg"
fetch "https://framerusercontent.com/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg?scale-down-to=1024" "assets/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg"
fetch "https://framerusercontent.com/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg?scale-down-to=2048" "assets/images/adA3ca5MJSdYVtT9ZmtqJigs.jpg"
fetch "https://framerusercontent.com/images/cDcsV8kitOIP6wus6TFe55S6Hw.png" "assets/images/cDcsV8kitOIP6wus6TFe55S6Hw.png"
fetch "https://framerusercontent.com/images/cDcsV8kitOIP6wus6TFe55S6Hw.png?scale-down-to=1024" "assets/images/cDcsV8kitOIP6wus6TFe55S6Hw.png"
fetch "https://framerusercontent.com/images/cDcsV8kitOIP6wus6TFe55S6Hw.png?scale-down-to=512" "assets/images/cDcsV8kitOIP6wus6TFe55S6Hw.png"
fetch "https://framerusercontent.com/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg" "assets/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg"
fetch "https://framerusercontent.com/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg?scale-down-to=1024" "assets/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg"
fetch "https://framerusercontent.com/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg?scale-down-to=2048" "assets/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg"
fetch "https://framerusercontent.com/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg?scale-down-to=4096" "assets/images/e3RFHas37fsz8NapHWnzO24Rq0E.jpg"
fetch "https://framerusercontent.com/images/efH3GoySpPrc2pWkXRQXroWHems.png" "assets/images/efH3GoySpPrc2pWkXRQXroWHems.png"
fetch "https://framerusercontent.com/images/efH3GoySpPrc2pWkXRQXroWHems.png?scale-down-to=1024" "assets/images/efH3GoySpPrc2pWkXRQXroWHems.png"
fetch "https://framerusercontent.com/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png" "assets/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png"
fetch "https://framerusercontent.com/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png?scale-down-to=1024" "assets/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png"
fetch "https://framerusercontent.com/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png?scale-down-to=512" "assets/images/mAOu3A5k1wgzKstAFlC0xzkD8Bg.png"
fetch "https://framerusercontent.com/images/sZ3PTm542DAM4Bn6XjcOyb1gV3M.png" "assets/images/sZ3PTm542DAM4Bn6XjcOyb1gV3M.png"
fetch "https://framerusercontent.com/images/sZ3PTm542DAM4Bn6XjcOyb1gV3M.png?scale-down-to=1024" "assets/images/sZ3PTm542DAM4Bn6XjcOyb1gV3M.png"
fetch "https://framerusercontent.com/images/tpGFIq7ObwXoiJyNP1brE9tUM.png" "assets/images/tpGFIq7ObwXoiJyNP1brE9tUM.png"
fetch "https://framerusercontent.com/images/tpGFIq7ObwXoiJyNP1brE9tUM.png?scale-down-to=1024" "assets/images/tpGFIq7ObwXoiJyNP1brE9tUM.png"
fetch "https://framerusercontent.com/images/tpGFIq7ObwXoiJyNP1brE9tUM.png?scale-down-to=512" "assets/images/tpGFIq7ObwXoiJyNP1brE9tUM.png"
fetch "https://framerusercontent.com/images/uJ8s5QaULeThA2JRoHUeOECmuM.png" "assets/images/uJ8s5QaULeThA2JRoHUeOECmuM.png"
fetch "https://framerusercontent.com/images/uJ8s5QaULeThA2JRoHUeOECmuM.png?scale-down-to=1024" "assets/images/uJ8s5QaULeThA2JRoHUeOECmuM.png"
fetch "https://framerusercontent.com/images/uJ8s5QaULeThA2JRoHUeOECmuM.png?scale-down-to=512" "assets/images/uJ8s5QaULeThA2JRoHUeOECmuM.png"

echo ""
echo "=== Fonts ==="
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mv0iQg.woff2" "assets/fonts/google-6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mv0iQg.woff2"
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mvIiQvTm.woff2" "assets/fonts/google-6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mvIiQvTm.woff2"
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mvMiQvTm.woff2" "assets/fonts/google-6NUs8FyLNQOQZAnv9ZwNjucMHVn85Ni7emAe9lKqZTnbB-gzTK0K1ChJdt9vIVYX9G37lvd9mvMiQvTm.woff2"
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c0qv86Rg.woff2" "assets/fonts/google-6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c0qv86Rg.woff2"
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c1qv86Rg.woff2" "assets/fonts/google-6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c1qv86Rg.woff2"
fetch "https://fonts.gstatic.com/s/fraunces/v37/6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c7qv8.woff2" "assets/fonts/google-6NUu8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58nib14c7qv8.woff2"
fetch "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2" "assets/fonts/0E7IMbDzcGABpBwwqNEt60wU0w.woff2"
fetch "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2" "assets/fonts/1K3W8DizY3v4emK8Mb08YHxTbs.woff2"
fetch "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2" "assets/fonts/1ZFS7N918ojhhd0nQWdj3jz4w.woff2"
fetch "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2" "assets/fonts/2A4Xx7CngadFGlVV4xrO06OBHY.woff2"
fetch "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2" "assets/fonts/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2"
fetch "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2" "assets/fonts/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2"
fetch "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2" "assets/fonts/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2"
fetch "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2" "assets/fonts/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2"
fetch "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2" "assets/fonts/6mJuEAguuIuMog10gGvH5d3cl8.woff2"
fetch "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2" "assets/fonts/867QObYax8ANsfX4TGEVU9YiCM.woff2"
fetch "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2" "assets/fonts/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2"
fetch "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2" "assets/fonts/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2"
fetch "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2" "assets/fonts/DOfvtmE1UplCq161m6Hj8CSQYg.woff2"
fetch "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2" "assets/fonts/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2"
fetch "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2" "assets/fonts/DolVirEGb34pEXEp8t8FQBSK4.woff2"
fetch "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2" "assets/fonts/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2"
fetch "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2" "assets/fonts/EOr0mi4hNtlgWNn9if640EZzXCo.woff2"
fetch "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2" "assets/fonts/GIryZETIX4IFypco5pYZONKhJIo.woff2"
fetch "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2" "assets/fonts/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2"
fetch "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2" "assets/fonts/H89BbHkbHDzlxZzxi8uPzTsp90.woff2"
fetch "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2" "assets/fonts/JEXmejW8mXOYMtt0hyRg811kHac.woff2"
fetch "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2" "assets/fonts/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2"
fetch "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2" "assets/fonts/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2"
fetch "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2" "assets/fonts/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2"
fetch "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2" "assets/fonts/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2"
fetch "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2" "assets/fonts/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2"
fetch "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2" "assets/fonts/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2"
fetch "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2" "assets/fonts/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2"
fetch "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2" "assets/fonts/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2"
fetch "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2" "assets/fonts/VgYFWiwsAC5OYxAycRXXvhze58.woff2"
fetch "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2" "assets/fonts/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2"
fetch "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2" "assets/fonts/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2"
fetch "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2" "assets/fonts/b6Y37FthZeALduNqHicBT6FutY.woff2"
fetch "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2" "assets/fonts/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2"
fetch "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2" "assets/fonts/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2"
fetch "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2" "assets/fonts/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2"
fetch "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2" "assets/fonts/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2"
fetch "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2" "assets/fonts/khkJkwSL66WFg8SX6Wa726c.woff2"
fetch "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2" "assets/fonts/ksvR4VsLksjpSwnC2fPgHRNMw.woff2"
fetch "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2" "assets/fonts/lEJLP4R0yuCaMCjSXYHtJw72M.woff2"
fetch "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2" "assets/fonts/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2"
fetch "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2" "assets/fonts/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2"
fetch "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2" "assets/fonts/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2"
fetch "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2" "assets/fonts/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2"
fetch "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2" "assets/fonts/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2"
fetch "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2" "assets/fonts/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2"
fetch "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2" "assets/fonts/vFzuJY0c65av44uhEKB6vyjFMg.woff2"
fetch "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2" "assets/fonts/vQyevYAyHtARFwPqUzQGpnDs.woff2"
fetch "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2" "assets/fonts/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2"
fetch "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2" "assets/fonts/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2"

echo ""
echo "=== Done ==="
echo "Images: $(ls assets/images/ | wc -l)"
echo "Fonts:  $(ls assets/fonts/ | wc -l)"
